export const SET_LOADING = 'SET_LOADING';
export const SET_QUERY = 'SET_QUERY';
export const SET_ERROR = 'SET_ERROR';
export const FETCH_PEOPLE_REQUEST = 'FETCH_PEOPLE_REQUEST';
export const FETCH_MEMBER_REQUEST = 'FETCH_MEMBER_REQUEST';
export const EDIT_MEMBER_REQUEST = 'EDIT_MEMBER_REQUEST';
